# An ansible playbook to prepare container image with podman
---
- hosts: all
  tasks:
  # - debug:
  #     msg: "User: {{ ansible_user_id }}"
  - dnf:
      name: '{{ item }}'
      state: latest
      enablerepo: updates-testing
    with_items:
      - nss_wrapper
      - podman
      - conmon
      - shadow-utils
  - user:
      name: podm
      create_home: yes
      home: /home/podm
  - file:
      state: directory
      path: /home
      mode: 0777
      recurse: yes
  - copy:
      src: ./passwd
      dest: /home/podm/passwd
      mode: 0777
  - copy:
      src: ./subuid
      dest: /etc/subuid
      mode: 0644
  - copy:
      src: ./subgid
      dest: /etc/subgid
      mode: 0644
